In [13]:
import pandas as pd

df = pd.read_csv("dataset.csv")
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [14]:
df.shape

(114000, 21)

In [15]:
## Check for duplicate tracks

duplicate_tracks = df['track_id'].duplicated().sum()
duplicate_tracks

24259

In [16]:
df_before = len(df)
df_before

114000

In [17]:
# Remove duplicate track_ids, keeping the first occurrence

df = df.drop_duplicates(subset='track_id', keep='first')
df_after = len(df)

print(f"Rows before: {df_before:,}")
print(f"Rows after: {df_after:,}")
print(f"Duplicates removed: {df_before - df_after:,}")
print(f"\n✓ Clean dataset now has {df_after:,} unique tracks")

Rows before: 114,000
Rows after: 89,741
Duplicates removed: 24,259

✓ Clean dataset now has 89,741 unique tracks

#####  Check for Missing Values

In [18]:
missing_count = df.isnull().sum()
missing_count

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [19]:
df = df.dropna()
df.shape

(89740, 21)

In [20]:
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [21]:
df.shape

(89740, 21)

In [22]:
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [23]:
# current values in explicit column
print("Current values in 'explicit' column:")
print(df['explicit'].value_counts())
print(f"\nData type: {df['explicit'].dtype}")

Current values in 'explicit' column:
explicit
False    82036
True      7704
Name: count, dtype: int64

Data type: bool

In [24]:
df["explicit"] = df.explicit.map({True:1 , False:0})
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,0,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,0,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,0,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,0,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,0,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [25]:
# Verify the conversion
print("\n✓ After conversion:")
print(df['explicit'].value_counts())
print(f"Data type: {df['explicit'].dtype}")

✓ After conversion:
explicit
0    82036
1     7704
Name: count, dtype: int64
Data type: int64

In [33]:
# unique genres exist
print(f"Total unique genres: {df['track_genre'].nunique()}")
print(f"\nGenre distribution (top 20):")
print(df['track_genre'].value_counts().head(20))

# See all genre names
print(f"\nAll genre names:")
print(sorted(df['track_genre'].unique()))

Total unique genres: 113

Genre distribution (top 20):
track_genre
acoustic         1000
alt-rock          999
tango             999
ambient           999
afrobeat          999
cantopop          999
bluegrass         998
forro             998
study             998
chicago-house     998
disney            998
sleep             997
heavy-metal       997
breakbeat         997
black-metal       996
j-idol            995
happy             995
anime             995
club              994
comedy            990
Name: count, dtype: int64

All genre names:
['acoustic', 'afrobeat', 'alt-rock', 'alternative', 'ambient', 'anime', 'black-metal', 'bluegrass', 'blues', 'brazil', 'breakbeat', 'british', 'cantopop', 'chicago-house', 'children', 'chill', 'classical', 'club', 'comedy', 'country', 'dance', 'dancehall', 'death-metal', 'deep-house', 'detroit-techno', 'disco', 'disney', 'drum-and-bass', 'dub', 'dubstep', 'edm', 'electro', 'electronic', 'emo', 'folk', 'forro', 'french', 'funk', 'garage', 'german', 'gospel', 'goth', 'grindcore', 'groove', 'grunge', 'guitar', 'happy', 'hard-rock', 'hardcore', 'hardstyle', 'heavy-metal', 'hip-hop', 'honky-tonk', 'house', 'idm', 'indian', 'indie', 'indie-pop', 'industrial', 'iranian', 'j-dance', 'j-idol', 'j-pop', 'j-rock', 'jazz', 'k-pop', 'kids', 'latin', 'latino', 'malay', 'mandopop', 'metal', 'metalcore', 'minimal-techno', 'mpb', 'new-age', 'opera', 'pagode', 'party', 'piano', 'pop', 'pop-film', 'power-pop', 'progressive-house', 'psych-rock', 'punk', 'punk-rock', 'r-n-b', 'reggae', 'reggaeton', 'rock', 'rock-n-roll', 'rockabilly', 'romance', 'sad', 'salsa', 'samba', 'sertanejo', 'show-tunes', 'singer-songwriter', 'ska', 'sleep', 'soul', 'spanish', 'study', 'swedish', 'synth-pop', 'tango', 'techno', 'trance', 'trip-hop', 'turkish', 'world-music']

In [39]:
# Create super genre groupings (your cleaner format!)
genre_mapping = {
    "Metal": [
        "black-metal", "death-metal", "heavy-metal",
        "metal", "metalcore"
    ],
    "Rock": [
        "rock", "alt-rock", "hard-rock", "rock-n-roll",
        "psych-rock", "punk-rock", "indie-rock", "garage",
        "grunge", "progressive-rock"
    ],
    "Pop": [
        "pop", "pop-film", "power-pop", "dance",
        "disco", "synth-pop", "dancehall", "k-pop",
        "j-pop", "indie-pop"
    ],
    "Electronic": [
        "edm", "electro", "electronic",
        "techno", "house", "trance",
        "dubstep", "drum-and-bass", "hardstyle",
        "deep-house", "minimal-techno"
    ],
    "Hip-Hop": [
        "hip-hop", "rap", "trap", "trip-hop",
        "grindcore", "breakbeat"
    ],
    "R&B/Soul": [
        "r-n-b", "soul", "funk", "gospel"
    ],
    "Jazz/Blues": [
        "jazz", "blues", "bluegrass", "swing"
    ],
    "Classical": [
        "classical", "opera", "piano"
    ],
    "Acoustic": [
        "acoustic", "folk", "singer-songwriter",
        "indie", "songwriter"
    ],
    "Latin": [
        "latino", "latin", "salsa", "samba",
        "tango", "reggaeton", "spanish", "brazil",
        "MPB", "forro", "pagode", "sertanejo"
    ],
    "Country": [
        "country", "honky-tonk"
    ],
    "World": [
        "reggae", "ska", "world-music", "indian",
        "afrobeat", "iranian", "turkish",
        "malay", "mandopop", "cantopop", "french",
        "swedish", "german", "british"
    ],
    "Ambient": [
        "ambient", "chill", "sleep", "study",
        "new-age", "industrial"
    ],
    "Alternative": [
        "alternative", "emo", "goth",
        "punk", "hardcore",
        "postpunk", "screamo"
    ],
    "Other": [
        "children", "kids", "comedy", "anime",
        "disney", "movies", "show-tunes", "romance",
        "sad", "happy", "party", "work-out",
        "summer", "road-trip"
    ]
}

In [40]:
genre_map_flat = {}
for super_genre, genres in genre_mapping.items():
    for genre in genres:
        genre_map_flat[genre] = super_genre

# Apply the mapping
df['super_genre'] = df['track_genre'].map(genre_map_flat)

# For any genres not in our mapping, label them as 'Other'
df['super_genre'] = df['super_genre'].fillna('Other')

# Check the results
print("✓ Super Genre created!")
print(f"\nSuper Genre distribution:")
print(df['super_genre'].value_counts())

print(f"\nTotal Super Genres: {df['super_genre'].nunique()}")

✓ Super Genre created!

Super Genre distribution:
super_genre
Other          19919
World          11662
Latin           8396
Pop             8020
Electronic      7432
Rock            5950
Ambient         5785
Metal           3844
Hip-Hop         3728
Alternative     3229
Classical       2513
Acoustic        2502
Jazz/Blues      2460
R&B/Soul        2373
Country         1927
Name: count, dtype: int64

Total Super Genres: 15